package com.zjf.test;

/**
 * FrameModule generated by hbm2java
 */
//@Entity(table = "Frame_Module", id = "moduleguid", ignore_field = {"oldmodulecode" })
public class FrameModule extends BaseEntity implements Cloneable, Comparable<FrameModule>
{
    private static final long serialVersionUID = 1L;

    /**
     * 取得
     **/
    public String getModuleGuid() {
        return super.get("moduleGuid");
    }

    /**
     * 设置
     **/
    public void setModuleGuid(String moduleGuid) {
        super.set("moduleGuid", moduleGuid);
    }

    /**
     * 取得
     **/
    public String getModuleCode() {
        return super.get("moduleCode");

//        return (String)super.getNative("moduleCode");
//        return (String)super.getNative(EXunWebSocket.G(""));
    }

    /**
     * 设置
     **/
    public void setModuleCode(String moduleCode) {
        super.set("moduleCode", moduleCode);
    }

    /**
     * 取得
     **/
    public String getModuleName() {
        return super.get("moduleName");
    }

    /**
     * 设置
     **/
    public void setModuleName(String moduleName) {
        super.set("moduleName", moduleName);
    }

    /**
     * 取得
     **/
    public String getMoudleMenuName() {
        return super.get("moudleMenuName");
    }

    /**
     * 设置
     **/
    public void setMoudleMenuName(String moudleMenuName) {
        super.set("moudleMenuName", moudleMenuName);
    }

    /**
     * 取得
     **/
    public String getModuleUrl() {
        return super.get("moduleUrl");
    }

    /**
     * 设置
     **/
    public void setModuleUrl(String moduleUrl) {
        super.set("moduleUrl", moduleUrl);
    }

    /**
     * 取得
     **/
    public Integer getOrderNumber() {
        return super.getInt("orderNumber");
    }

    /**
     * 设置
     **/
    public void setOrderNumber(Integer orderNumber) {
        super.set("orderNumber", orderNumber);
    }

    /**
     * 取得
     **/
    public Boolean getIsDisable() {
        return super.getBoolean("isDisable");
    }

    /**
     * 设置
     **/
    public void setIsDisable(Boolean isDisable) {
        super.set("isDisable", isDisable);
    }

    /**
     * 取得
     **/
    public Boolean getIsBlank() {
        return super.getBoolean("isBlank");
    }

    /**
     * 设置
     **/
    public void setIsBlank(Boolean isBlank) {
        super.set("isBlank", isBlank);
    }

    /**
     * 取得
     **/
    public String getBigIconAddress() {
        return super.get("bigIconAddress");
    }

    /**
     * 设置
     **/
    public void setBigIconAddress(String bigIconAddress) {
        super.set("bigIconAddress", bigIconAddress);
    }

    /**
     * 取得
     **/
    public String getSmallIconAddress() {
        return super.get("smallIconAddress");
    }

    /**
     * 设置
     **/
    public void setSmallIconAddress(String smallIconAddress) {
        super.set("smallIconAddress", smallIconAddress);
    }

    /**
     * 取得
     **/
    public String getModuleType() {
        return super.get("moduleType");
    }

    /**
     * 设置
     **/
    public void setModuleType(String moduleType) {
        super.set("moduleType", moduleType);
    }

    /**
     * 取得
     **/
    public String getOldModuleCode() {
        return super.get("oldModuleCode");
    }

    /**
     * 设置
     **/
    public void setOldModuleCode(String oldModuleCode) {
        super.set("oldModuleCode", oldModuleCode);
    }

    /**
     * 取得是否由SOA同步
     **/
    public Integer getIsFromSOA() {
        return super.getInt("isFromSOA");
    }

    /**
     * 设置是否由SOA同步
     **/
    public void setIsFromSOA(Integer isFromSOA) {
        super.set("isFromSOA", isFromSOA);
    }

    /**
     * 取得是否可用
     **/
    public Integer getIsUse() {
        return super.getInt("isUse");
    }

    /**
     * 设置是否可用
     **/
    public void setIsUse(Integer isUse) {
        super.set("isUse", isUse);
    }

    /**
     * 取得是否隐藏菜单
     **/
    public Integer getIsAddOu() {
        return super.getInt("isAddOu");
    }

    /**
     * 设置是否隐藏菜单
     **/
    public void setIsAddOu(Integer isAddOu) {
        super.set("isaddou", isAddOu);
    }

    public int compareTo(FrameModule o2) {
        int result = -1;
        Integer o1Order = this.getOrderNumber();
        Integer o2Order = o2.getOrderNumber();
        // 同一层级需要按照排序号进行排序，其他按照code从小到大排序
        if (this.getModuleCode().length() == o2.getModuleCode().length()) {
            if (o1Order == null && o2Order == null) {
                result = 0;
            }
            else if (o1Order == null) {
                result = 1;
            }
            else if (o2Order == null) {
                result = -1;
            }
            else {
                result = o2Order - o1Order;
            }
        }
        else {
            result = this.getModuleCode().length() - o2.getModuleCode().length();
        }
        return result;

    }

    public FrameModule clone() {
        return (FrameModule) super.clone();
    }
}
